### PR TITLE
Support output spaces to arbitrary templates and cohorts

### PR DESCRIPTION
**Pull request by mattcieslak**
The HBCD data will be registered to MNIInfant+cohort templates. We want to make sure these file names are used in the qsirecon scalar mappers

### CODE REVIEW

**Comment by mattcieslak** [comment]
there would be a crash. Probably better to exit with an error than let it crash downstream?

**Comment by tsalo** [comment]
Oh I see that now:

https://github.com/PennLINC/qsirecon/blob/0b53f5338e635e307d3b21d1f91b9e6ea7328eb6/qsirecon/utils/bids.py#L204-L217

Users would get a pretty clear error message. Something like:

```
More than one acpc_to_template_xfm found.
Files found:
    /path/to/sub-01_from-ACPC_to-MNIInfant+1_mode-image_xfm.h5
    /path/to/sub-01_from-ACPC_to-MNIInfant+2_mode-image_xfm.h5
Query: {'datatype': 'anat', 'from': ['T1w', 'T2w', 'ACPC'], 'to': 'MNI152NLin2009cAsym', 'mode': 'image', 'suffix': 'xfm', 'extension': '.h5'}
```

**Comment by mattcieslak** [comment]
I'm happy with that error message!

**Comment by tsalo** [comment]
Actually, since the `to` value is set by QSIRecon as either MNI152NLin2009cAsym (default) or MNIInfant (infant mode), I think (1) you wouldn't get an error and (2) you won't catch `MNIInfant+<cohort>`. Does that sound right?

**Comment by mattcieslak** [comment]
In my local testing with the cohorts it still finds them

**Comment by tsalo** [comment]
Oh... maybe that's related to how `parse_file_entities` doesn't find the `+<cohort>` in the entities?

**Comment by mattcieslak** [comment]
Right, the query finds it while ignoring the cohort part

**Comment by tsalo** [comment]
I worry that's more of a convenient bug than a feature, but I also think we'll have plenty of notice if pybids starts parsing these plus signs correctly and searching 'MNIInfant' stops finding 'MNIInfant+1' etc.

**Comment by mattcieslak** [comment]
We'll definitely need to add a test for MNIInfant inputs, but it will be a big task to get simulated data that looks like HBCD

**Comment by tsalo** [comment]
I think SDCFlows has a few tests where they just generate a dataset layout from a dictionary and make sure that the queries work as expected. We could probably add something like that just to make sure the collection steps are working.

**Review by tsalo — APPROVED** [review]
I think things will change once we let users specify the output spaces they want, but this is a huge step in that direction. Everything looks good to me!

**Pull request merged**
