### PR TITLE
Fix QSIRecon Entrypoint

### LINKED ISSUE #75: QSIRecon entrypoint wrong in container
## Summary
QSIRecon is being looked for at `/opt/conda/envs/qsirecon/bin/qsirecon`, should be `/opt/conda/envs/qsiprep/bin/qsirecon`

### PR DESCRIPTION
**Pull request by smeisler**
Fixes #75

### CODE REVIEW

**Comment by tsalo** [comment]
I think you might need to move

```
derivatives/qsirecon-PYAFQ/sub-ABCD/dwi/sub-ABCD_acq-10per000_space-T1w_dwimap/bundles/sub-ABCD_acq-10per000_coordsys-RASMM_trkmethod-probCSD_recogmethod-AFQ_desc-LeftSuperiorLongitudinal_tractography.trk
derivatives/qsirecon-PYAFQ/sub-ABCD/dwi/sub-ABCD_acq-10per000_space-T1w_dwimap/viz_core_bundles/sub-ABCD_acq-10per000_coordsys-RASMM_trkmethod-probCSD_recogmethod-AFQ_desc-LeftSuperiorLongitudinalviz_dwi.html
```

to the list of optional outputs.

**Comment by tsalo** [comment]
You'll need to remove those files from the required inputs as well, since they were expected but not found.

**Comment by smeisler** [comment]
passing tests now, okay to merge?

**Comment by mattcieslak** [comment]
What happened in the pyafq outputs? Were some of the files in the wrong list?

**Comment by mattcieslak** [comment]
I missed the earlier conversation, looks good to me!

**Pull request merged**
