### PR TITLE
Fix space in ds_qsiprep_5tt_hsvs

### PR DESCRIPTION
**Pull request by tsalo**
Closes none, but addresses a bug identified by @araikes.

## Changes proposed in this pull request

- Hardcode space entity in `ds_qsiprep_5tt_hsvs` as ACPC, not T1w.

### CODE REVIEW

**Comment by tsalo** [comment]
@mattcieslak should I also change the T1w default here?

https://github.com/PennLINC/qsirecon/blob/c1b843541304d5374b126562758e412cc0e04116/qsirecon/workflows/recon/utils.py#L54-L60

The space parameter isn't actually used, so it might be better to just remove it.

**Comment by mattcieslak** [comment]
> The space parameter isn't actually used, so it might be better to just remove it.

I think we should remove it

**Review by mattcieslak — APPROVED** [review]
Thanks!

**Review by mattcieslak — APPROVED** [review]
Those spaces in the csv file may be coming from [here](https://github.com/PennLINC/qsirecon/blob/8545323d8ae494108a99b0e3ba288386f53e8944/docs/update_scalardefs.py#L70).

**Pull request merged**
