### PR TITLE
[CI] Speed up pyafq test

### PR DESCRIPTION
**Pull request by mattcieslak**
This removes a couple bundles from the pyafq tests. hopefully this will speed up the test a bit

### CODE REVIEW

**Comment by mattcieslak** [comment]
@36000 would you mind taking a look at this PR? I'm not sure where I'm going wrong, but it looks like I can't get pyafq to run with more than 1 cpu. Here's the [resource usage](https://app.circleci.com/pipelines/github/PennLINC/qsirecon/131/workflows/e40d69ca-d25e-43cd-8934-dc713b476e0f/jobs/1450/resources) from the previous run. where it should have been using 8 cpus.

**Comment by 36000** [comment]
It would be both the prealign and mapping. These are what the filenames look like for the stanford hardi dataset:
sub-01_ses-01_desc-prealign_from-DWI_to-MNI_xform.npy
sub-01_ses-01_desc-mapping_from-DWI_to-MNI_xform.nii.gz

**Comment by 36000** [comment]
I can do this, but I won't be free to do this for about a month!

**Comment by mattcieslak** [comment]
oh, pyafq isn't using the mni transform from the preprocessed data? Is that what the previous itk_file code was doing?

**Comment by mattcieslak** [comment]
In the meantime is it possible to make the registration run in parallel?

**Comment by 36000** [comment]
That was what the previous ITK file code was doing. But I don't think the ITK code works anymore... something updated and changed its format. I spent some time but I couldn't figure out how to convert it anymore. Maybe nitransforms will solve this problem.

Anyways, since this is just a smoketest, we could also just use IdentityMap. It will just resample the ROIs from mni into subject space, which is wrong, but probably close enough for testing purposes. Especially for these few bundles

**Comment by 36000** [comment]
So:
"mapping_definition": 'AffMap(affine_kwargs={"level_iters": [10, 10, 10]})',
becomes:
"mapping_definition": 'IdentityMap()',

**Comment by mattcieslak** [comment]
@36000 It didn't like that https://app.circleci.com/pipelines/github/PennLINC/qsirecon/134/workflows/cd025d5e-b362-4ca5-8eaf-cd378a841abc/jobs/1494

**Comment by 36000** [comment]
I see the problem. We will need to change pyAFQ. The PR is here: https://github.com/yeatmanlab/pyAFQ/pull/1153

**Comment by 36000** [comment]
how hard would it be to use that branch for the tests? To see if that fixes it?

**Comment by mattcieslak** [comment]
I'll probably just put this on pause until your PR makes it into PyAFQ. Could you point me to the area in PyAFQ where the itk map from qsiprep would be used? I may be able to get it working

**Comment by 36000** [comment]
This file holds the API for mapping, and FNIRTmap might be a good template for how to import mapping from another software:
https://github.com/yeatmanlab/pyAFQ/blob/34c681750fa045f02946fced5640e1c1d76a5ec5/AFQ/definitions/mapping.py#L34

**Pull request merged**
