### PR TITLE
[ENH] Start HCP ingress functionality

### PR DESCRIPTION
**Pull request by smeisler**
## Changes proposed in this pull request
Add HCP ingress functions

## Documentation that should be reviewed
None yet, will be added in PR later

### CODE REVIEW

**Comment by smeisler** [comment]
@tsalo @mattcieslak running into some issues. I showed Matt earlier, but it looks like during workflow building, QSIPrep is checking for the BIDSified file (e.g., `/bids/sub-100307/dwi/sub-100307_dwi.nii.gz`) before it is produced. This precludes Nipype workflows from starting, and therefore no working directory as well.

**Comment by tsalo** [comment]
Is there a particular node that expects the file to exist?

**Comment by smeisler** [comment]
Yes
```
summary = pe.Node(
        SubjectSummary(
            subject_id=subject_id,
            subjects_dir=config.execution.fs_subjects_dir,
            std_spaces=["MNIInfant" if config.workflow.infant else "MNI152NLin2009cAsym"],
            nstd_spaces=[],
            dwi=dwi_files,
        ),
        name="summary",
        run_without_submitting=True,
    )
```

**Comment by smeisler** [comment]
Full traceback:
```
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/cli/workflow.py", line 140, in build_workflow
    retval["workflow"] = init_qsirecon_wf()
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/base.py", line 61, in init_qsirecon_wf
    single_subject_wf = init_single_subject_recon_wf(subject_id=subject_id)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsirecon/workflows/base.py", line 301, in init_single_subject_recon_wf
    SubjectSummary(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 563, in __init__
    super(SimpleInterface, self).__init__(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 424, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_types.py", line 2699, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 582, in __init__
    super().__init__(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_handlers.py", line 873, in validate
    return self.slow_validate(object, name, value)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/trait_handlers.py", line 881, in slow_validate
    self.error(object, name, value)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'dwi' trait of a SubjectSummaryInputSpec instance must be a pathlike object or string representing an existing file or a list of items which are a pathlike object or string representing an existing file, but a value of '/bids/sub-100307/dwi/sub-100307_dwi.nii.gz' <class 'str'> was specified.
```

**Comment by tsalo** [comment]
We could switch it from requiring existing files to just requiring filenames. What about adding `run_without_submitting=True,` to the HCPIngress node?

**Comment by smeisler** [comment]
adding `run_without_submitting=True` did not fix it, same message

**Comment by tsalo** [comment]
In that case I recommend changing the SubjectSummary interface to not require an existing file.

**Comment by smeisler** [comment]
@tsalo that seems to have worked!

**Comment by smeisler** [comment]
Now working on it at https://github.com/PennLINC/ingress2qsirecon/pull/1

**Comment by smeisler** [comment]
Closing in favor of #102

**Pull request closed without merging**
